// resources/src/pages/Reports.tsx
import { useState, useEffect } from "react";
import { Layout } from "@/components/layout/Layout";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, LineChart, Line, Legend } from 'recharts';
import { Download, TrendingUp, Users, MessageSquare, Target, FileText, Calendar } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import analyticsService, { ChartData, ComprehensiveReport } from "@/services/analyticsService";

export default function Reports() {
  const { toast } = useToast();
  const [chartData, setChartData] = useState<ChartData | null>(null);
  const [period, setPeriod] = useState<string>('last_7_days');
  const [loading, setLoading] = useState(true);
  const [startDate, setStartDate] = useState<string>(
    new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0]
  );
  const [endDate, setEndDate] = useState<string>(
    new Date().toISOString().split('T')[0]
  );

  useEffect(() => {
    loadChartData();
  }, [period]);

  const loadChartData = async () => {
    try {
      setLoading(true);
      const data = await analyticsService.getChartData(period);
      setChartData(data);
    } catch (error) {
      console.error('Failed to load chart data:', error);
      toast({
        title: "Erreur",
        description: "Impossible de charger les données du graphique",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const handleExportPdf = async () => {
    try {
      toast({
        title: "Export en cours",
        description: "Génération du rapport PDF...",
      });
      const blob = await analyticsService.exportPdf(startDate, endDate);
      analyticsService.downloadFile(blob, `rapport_analytics_${startDate}_${endDate}.pdf`);
      toast({
        title: "Export réussi",
        description: "Le rapport PDF a été téléchargé",
      });
    } catch (error) {
      console.error('Export PDF failed:', error);
      toast({
        title: "Erreur d'export",
        description: "Impossible de générer le rapport PDF",
        variant: "destructive"
      });
    }
  };

  const handleExportExcel = async () => {
    try {
      toast({
        title: "Export en cours",
        description: "Génération du rapport Excel...",
      });
      const blob = await analyticsService.exportExcel(startDate, endDate);
      analyticsService.downloadFile(blob, `rapport_analytics_${startDate}_${endDate}.xlsx`);
      toast({
        title: "Export réussi",
        description: "Le rapport Excel a été téléchargé",
      });
    } catch (error) {
      console.error('Export Excel failed:', error);
      toast({
        title: "Erreur d'export",
        description: "Impossible de générer le rapport Excel",
        variant: "destructive"
      });
    }
  };

  const handleExportCsv = async () => {
    try {
      toast({
        title: "Export en cours",
        description: "Génération du rapport CSV...",
      });
      const blob = await analyticsService.exportCsv(startDate, endDate);
      analyticsService.downloadFile(blob, `rapport_analytics_${startDate}_${endDate}.csv`);
      toast({
        title: "Export réussi",
        description: "Le rapport CSV a été téléchargé",
      });
    } catch (error) {
      console.error('Export CSV failed:', error);
      toast({
        title: "Erreur d'export",
        description: "Impossible de générer le rapport CSV",
        variant: "destructive"
      });
    }
  };

  const monthlyData = chartData ? chartData.labels.map((label, index) => ({
    month: label,
    sent: chartData.datasets[0].data[index],
    delivered: chartData.datasets[1].data[index],
    failed: chartData.datasets[2].data[index]
  })) : [];
  return (
    <Layout title="Analytics & Rapports">
      <div className="space-y-6">
        {/* Header with Period Selector */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold">Analytics & Rapports</h1>
            <p className="text-muted-foreground mt-1">Analyse détaillée de vos campagnes SMS</p>
          </div>
          <select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="px-4 py-2 border border-border rounded-lg bg-background focus:outline-none focus:ring-2 focus:ring-primary"
          >
            <option value="week">Cette semaine</option>
            <option value="month">Ce mois</option>
            <option value="last_7_days">7 derniers jours</option>
            <option value="last_30_days">30 derniers jours</option>
            <option value="year">Cette année</option>
          </select>
        </div>

        {/* Chart Section */}
        <Card>
          <CardHeader>
            <CardTitle>Évolution des SMS</CardTitle>
            <CardDescription>
              Suivi quotidien des SMS envoyés, délivrés et échoués
            </CardDescription>
          </CardHeader>
          <CardContent>
            {loading ? (
              <div className="flex items-center justify-center h-[300px]">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
              </div>
            ) : monthlyData.length > 0 ? (
              <ResponsiveContainer width="100%" height={350}>
                <LineChart data={monthlyData}>
                  <CartesianGrid strokeDasharray="3 3" />
                  <XAxis dataKey="month" />
                  <YAxis />
                  <Tooltip />
                  <Legend />
                  <Line type="monotone" dataKey="sent" stroke="#3B82F6" name="Envoyés" strokeWidth={2} />
                  <Line type="monotone" dataKey="delivered" stroke="#10B981" name="Délivrés" strokeWidth={2} />
                  <Line type="monotone" dataKey="failed" stroke="#EF4444" name="Échoués" strokeWidth={2} />
                </LineChart>
              </ResponsiveContainer>
            ) : (
              <div className="flex items-center justify-center h-[300px] text-muted-foreground">
                Aucune donnée disponible pour cette période
              </div>
            )}
          </CardContent>
        </Card>

        {/* Export Section */}
        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <div>
                <CardTitle>Exporter les Rapports</CardTitle>
                <CardDescription>
                  Téléchargez vos rapports d'analytics dans différents formats
                </CardDescription>
              </div>
              <FileText className="h-8 w-8 text-muted-foreground" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="space-y-4">
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <div>
                  <label className="block text-sm font-medium mb-2">Date de début</label>
                  <input
                    type="date"
                    value={startDate}
                    onChange={(e) => setStartDate(e.target.value)}
                    className="w-full px-3 py-2 border border-border rounded-lg bg-background focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                </div>
                <div>
                  <label className="block text-sm font-medium mb-2">Date de fin</label>
                  <input
                    type="date"
                    value={endDate}
                    onChange={(e) => setEndDate(e.target.value)}
                    className="w-full px-3 py-2 border border-border rounded-lg bg-background focus:outline-none focus:ring-2 focus:ring-primary"
                  />
                </div>
              </div>
              <div className="flex flex-wrap gap-4 pt-4">
                <Button variant="outline" onClick={handleExportPdf}>
                  <Download className="w-4 h-4 mr-2" />
                  Exporter en PDF
                </Button>
                <Button variant="outline" onClick={handleExportExcel}>
                  <Download className="w-4 h-4 mr-2" />
                  Exporter en Excel
                </Button>
                <Button variant="outline" onClick={handleExportCsv}>
                  <Download className="w-4 h-4 mr-2" />
                  Exporter en CSV
                </Button>
              </div>
              <p className="text-sm text-muted-foreground mt-2">
                Les exports incluent: résumé général, tendances, répartition par opérateur, top campagnes, et détail quotidien.
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </Layout>
  );
}

// resources/src/views/Reports.vue
<template>
  <MainLayout>
    <div class="p-8">
      <div class="mb-8 flex items-center justify-between">
        <div>
          <div class="flex items-center gap-2">
            <ChartBarIcon class="w-8 h-8 text-primary" />
            <h1 class="text-3xl font-bold">Rapports & Statistiques</h1>
          </div>
          <p class="text-muted-foreground mt-2">Analysez les performances de vos campagnes</p>
        </div>
        <div class="flex gap-3">
          <button
            @click="exportReport('pdf')"
            :disabled="exporting"
            class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2"
          >
            <ArrowDownTrayIcon class="w-4 h-4" />
            <span>Exporter PDF</span>
          </button>
          <button
            @click="exportReport('excel')"
            :disabled="exporting"
            class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2"
          >
            <ArrowDownTrayIcon class="w-4 h-4" />
            <span>Exporter Excel</span>
          </button>
          <button
            @click="exportReport('csv')"
            :disabled="exporting"
            class="inline-flex items-center justify-center gap-2 whitespace-nowrap rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-10 px-4 py-2"
          >
            <ArrowDownTrayIcon class="w-4 h-4" />
            <span>Exporter CSV</span>
          </button>
        </div>
      </div>

      <div v-if="loading" class="flex items-center justify-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>

      <div v-else>
        <!-- Période de sélection -->
        <div class="rounded-lg border bg-card p-4 mb-6">
          <div class="flex items-center gap-4">
            <div class="flex-1">
              <label class="text-sm font-medium mb-1 block">Date de début</label>
              <input
                v-model="startDate"
                type="date"
                @change="loadDashboard"
                class="flex h-9 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
              />
            </div>
            <div class="flex-1">
              <label class="text-sm font-medium mb-1 block">Date de fin</label>
              <input
                v-model="endDate"
                type="date"
                @change="loadDashboard"
                class="flex h-9 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
              />
            </div>
          </div>
        </div>

        <!-- Vue d'ensemble -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <div class="rounded-lg border bg-card p-6">
            <div class="flex items-center gap-2 mb-4">
              <PaperAirplaneIcon class="w-5 h-5 text-primary" />
              <h3 class="font-semibold text-sm">SMS Envoyés</h3>
            </div>
            <div class="text-3xl font-bold text-primary mb-2">{{ formatNumber(dashboard?.overview.sms_sent || 0) }}</div>
            <div class="flex items-center gap-2">
              <ArrowTrendingUpIcon v-if="dashboard?.trends.sms_sent_change > 0" class="w-4 h-4 text-success" />
              <ArrowTrendingDownIcon v-else class="w-4 h-4 text-destructive" />
              <p class="text-xs" :class="dashboard?.trends.sms_sent_change > 0 ? 'text-success' : 'text-destructive'">
                {{ dashboard?.trends.sms_sent_change > 0 ? '+' : '' }}{{ dashboard?.trends.sms_sent_change.toFixed(1) }}%
              </p>
            </div>
          </div>

          <div class="rounded-lg border bg-card p-6">
            <div class="flex items-center gap-2 mb-4">
              <CheckCircleIcon class="w-5 h-5 text-success" />
              <h3 class="font-semibold text-sm">Taux de livraison</h3>
            </div>
            <div class="text-3xl font-bold text-success mb-2">{{ dashboard?.overview.success_rate.toFixed(1) }}%</div>
            <p class="text-xs text-muted-foreground">{{ dashboard?.overview.sms_delivered.toLocaleString() }} livrés</p>
          </div>

          <div class="rounded-lg border bg-card p-6">
            <div class="flex items-center gap-2 mb-4">
              <RocketLaunchIcon class="w-5 h-5 text-primary" />
              <h3 class="font-semibold text-sm">Campagnes</h3>
            </div>
            <div class="text-3xl font-bold mb-2">{{ dashboard?.overview.campaigns_executed || 0 }}</div>
            <div class="flex items-center gap-2">
              <ArrowTrendingUpIcon v-if="dashboard?.trends.campaigns_change > 0" class="w-4 h-4 text-success" />
              <ArrowTrendingDownIcon v-else class="w-4 h-4 text-destructive" />
              <p class="text-xs" :class="dashboard?.trends.campaigns_change > 0 ? 'text-success' : 'text-destructive'">
                {{ dashboard?.trends.campaigns_change > 0 ? '+' : '' }}{{ dashboard?.trends.campaigns_change.toFixed(1) }}%
              </p>
            </div>
          </div>

          <div class="rounded-lg border bg-card p-6">
            <div class="flex items-center gap-2 mb-4">
              <CheckBadgeIcon class="w-5 h-5 text-warning" />
              <h3 class="font-semibold text-sm">Coût Total</h3>
            </div>
            <div class="text-3xl font-bold mb-2">{{ dashboard?.overview.total_cost.toLocaleString() }} FCFA</div>
            <p class="text-xs text-muted-foreground">{{ dashboard?.overview.average_cost_per_sms.toFixed(2) }} FCFA/SMS</p>
          </div>
        </div>

        <!-- Providers Distribution -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <div class="rounded-lg border bg-card p-6">
            <div class="flex items-center gap-2 mb-6">
              <ChartBarIcon class="w-5 h-5 text-primary" />
              <h3 class="font-semibold">Distribution par opérateur</h3>
            </div>
            <div class="space-y-4">
              <div>
                <div class="flex items-center justify-between mb-2">
                  <span class="text-sm font-medium">Airtel</span>
                  <span class="text-sm font-semibold">{{ dashboard?.providers.airtel.percentage.toFixed(1) }}%</span>
                </div>
                <div class="w-full bg-gray-200 rounded-full h-3">
                  <div
                    class="bg-red-500 h-3 rounded-full transition-all"
                    :style="{ width: dashboard?.providers.airtel.percentage + '%' }"
                  ></div>
                </div>
                <p class="text-xs text-muted-foreground mt-1">{{ dashboard?.providers.airtel.count.toLocaleString() }} SMS</p>
              </div>
              <div>
                <div class="flex items-center justify-between mb-2">
                  <span class="text-sm font-medium">Moov</span>
                  <span class="text-sm font-semibold">{{ dashboard?.providers.moov.percentage.toFixed(1) }}%</span>
                </div>
                <div class="w-full bg-gray-200 rounded-full h-3">
                  <div
                    class="bg-blue-500 h-3 rounded-full transition-all"
                    :style="{ width: dashboard?.providers.moov.percentage + '%' }"
                  ></div>
                </div>
                <p class="text-xs text-muted-foreground mt-1">{{ dashboard?.providers.moov.count.toLocaleString() }} SMS</p>
              </div>
            </div>
          </div>

          <div class="rounded-lg border bg-card p-6">
            <div class="flex items-center gap-2 mb-6">
              <TrophyIcon class="w-5 h-5 text-primary" />
              <h3 class="font-semibold">Top Campagnes</h3>
            </div>
            <div v-if="dashboard?.campaigns.length === 0" class="text-center py-8">
              <ChartBarIcon class="w-12 h-12 text-muted-foreground mx-auto mb-2" />
              <p class="text-sm text-muted-foreground">Aucune campagne</p>
            </div>
            <div v-else class="space-y-3">
              <div v-for="campaign in dashboard?.campaigns.slice(0, 5)" :key="campaign.id" class="flex items-center justify-between p-3 bg-muted/50 rounded-lg">
                <div class="flex-1">
                  <div class="font-medium text-sm">{{ campaign.name }}</div>
                  <div class="text-xs text-muted-foreground">{{ campaign.messages_sent.toLocaleString() }} envois</div>
                </div>
                <span class="text-xs px-2 py-1 rounded-full" :class="getStatusClass(campaign.status)">
                  {{ campaign.status }}
                </span>
              </div>
            </div>
          </div>
        </div>

        <!-- Analyse des coûts -->
        <div class="rounded-lg border bg-card p-6 mb-8">
          <div class="flex items-center gap-2 mb-6">
            <ChartBarIcon class="w-5 h-5 text-primary" />
            <h3 class="font-semibold">Analyse des coûts</h3>
          </div>
          <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <div class="text-sm text-muted-foreground mb-1">Coût Airtel</div>
              <div class="text-2xl font-bold">{{ dashboard?.cost_analysis.airtel_cost.toLocaleString() }} FCFA</div>
            </div>
            <div>
              <div class="text-sm text-muted-foreground mb-1">Coût Moov</div>
              <div class="text-2xl font-bold">{{ dashboard?.cost_analysis.moov_cost.toLocaleString() }} FCFA</div>
            </div>
            <div>
              <div class="text-sm text-muted-foreground mb-1">Moyenne journalière</div>
              <div class="text-2xl font-bold">{{ dashboard?.cost_analysis.average_daily_cost.toLocaleString() }} FCFA</div>
            </div>
          </div>
        </div>

        <!-- Distribution horaire -->
        <div class="rounded-lg border bg-card p-6">
          <div class="flex items-center gap-2 mb-6">
            <ClockIcon class="w-5 h-5 text-primary" />
            <h3 class="font-semibold">Distribution horaire des envois</h3>
          </div>
          <div v-if="dashboard?.hourly_distribution.length === 0" class="text-center py-12">
            <p class="text-muted-foreground">Aucune donnée disponible</p>
          </div>
          <div v-else class="grid grid-cols-12 gap-2">
            <div
              v-for="hour in dashboard?.hourly_distribution"
              :key="hour.hour"
              class="flex flex-col items-center"
            >
              <div
                class="w-full bg-primary/20 rounded-t"
                :style="{ height: getBarHeight(hour.count) + 'px' }"
              >
                <div
                  class="w-full bg-primary rounded-t transition-all"
                  :style="{ height: '100%' }"
                  :title="`${hour.count} SMS à ${hour.hour}h`"
                ></div>
              </div>
              <div class="text-xs text-muted-foreground mt-1">{{ hour.hour }}h</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import MainLayout from '@/components/MainLayout.vue'
import {
  ChartBarIcon,
  PaperAirplaneIcon,
  CheckCircleIcon,
  ArrowTrendingUpIcon,
  ArrowTrendingDownIcon,
  RocketLaunchIcon,
  ClockIcon,
  CheckBadgeIcon,
  TrophyIcon,
  ArrowDownTrayIcon
} from '@heroicons/vue/24/outline'
import analyticsService, { type AnalyticsDashboard } from '@/services/analyticsService'
import { showSuccess, showError } from '@/utils/notifications'

const loading = ref(true)
const exporting = ref(false)
const dashboard = ref<AnalyticsDashboard | null>(null)

// Date range for filtering
const startDate = ref('')
const endDate = ref('')

// Set default date range (last 30 days)
function setDefaultDateRange() {
  const end = new Date()
  const start = new Date()
  start.setDate(start.getDate() - 30)

  endDate.value = end.toISOString().split('T')[0]
  startDate.value = start.toISOString().split('T')[0]
}

async function loadDashboard() {
  try {
    loading.value = true
    const response = await analyticsService.getDashboard('month')
    dashboard.value = response.data
  } catch (error: any) {
    console.error('Error loading dashboard:', error)
    showError(error.response?.data?.message || 'Erreur lors du chargement des statistiques')
  } finally {
    loading.value = false
  }
}

async function exportReport(format: 'pdf' | 'excel' | 'csv') {
  if (!startDate.value || !endDate.value) {
    showError('Veuillez sélectionner une période')
    return
  }

  try {
    exporting.value = true
    let blob: Blob
    let filename: string

    switch (format) {
      case 'pdf':
        blob = await analyticsService.exportPdf(startDate.value, endDate.value)
        filename = `rapport_${startDate.value}_${endDate.value}.pdf`
        break
      case 'excel':
        blob = await analyticsService.exportExcel(startDate.value, endDate.value)
        filename = `rapport_${startDate.value}_${endDate.value}.xlsx`
        break
      case 'csv':
        blob = await analyticsService.exportCsv(startDate.value, endDate.value)
        filename = `rapport_${startDate.value}_${endDate.value}.csv`
        break
    }

    analyticsService.downloadFile(blob, filename)
    showSuccess(`Rapport ${format.toUpperCase()} téléchargé avec succès`)
  } catch (error: any) {
    console.error('Error exporting report:', error)
    showError(error.response?.data?.message || 'Erreur lors de l\'export')
  } finally {
    exporting.value = false
  }
}

function formatNumber(num: number): string {
  if (num >= 1000000) {
    return `${(num / 1000000).toFixed(1)}M`
  }
  if (num >= 1000) {
    return `${(num / 1000).toFixed(1)}K`
  }
  return num.toString()
}

function getStatusClass(status: string): string {
  const statusLower = status.toLowerCase()
  if (statusLower === 'actif' || statusLower === 'active' || statusLower === 'completed') {
    return 'bg-success/10 text-success'
  }
  if (statusLower === 'planifié' || statusLower === 'scheduled' || statusLower === 'pending') {
    return 'bg-warning/10 text-warning'
  }
  if (statusLower === 'terminé' || statusLower === 'sent') {
    return 'bg-blue-100 text-blue-700'
  }
  return 'bg-muted text-muted-foreground'
}

function getBarHeight(count: number): number {
  if (!dashboard.value?.hourly_distribution.length) return 0
  const maxCount = Math.max(...dashboard.value.hourly_distribution.map(h => h.count))
  if (maxCount === 0) return 0
  return Math.max(20, (count / maxCount) * 100)
}

onMounted(() => {
  setDefaultDateRange()
  loadDashboard()
})
</script>
