// resources/src/views/Dashboard.vue
<template>
  <MainLayout>
    <div class="p-8">
      <div class="mb-8 flex justify-between items-center">
        <div>
          <h1 class="text-3xl font-bold text-foreground">Tableau de bord</h1>
          <p class="text-muted-foreground mt-2">Bienvenue {{ user?.name }}</p>
        </div>
        <div class="flex gap-2">
          <button
            v-for="period in periods"
            :key="period.value"
            @click="selectedPeriod = period.value"
            class="px-4 py-2 rounded-lg text-sm font-medium transition-colors"
            :class="selectedPeriod === period.value ? 'bg-primary text-primary-foreground' : 'bg-muted text-muted-foreground hover:bg-muted/80'"
          >
            {{ period.label }}
          </button>
        </div>
      </div>

      <!-- Chargement -->
      <div v-if="loading" class="flex items-center justify-center py-12">
        <div class="animate-spin rounded-full h-12 w-12 border-b-2 border-primary"></div>
      </div>

      <div v-else>
        <!-- Statistiques principales -->
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6 mb-8">
          <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
            <div class="flex items-center justify-between">
              <h3 class="text-sm font-medium text-muted-foreground">Messages Envoyés</h3>
              <PaperAirplaneIcon class="w-8 h-8 text-primary" />
            </div>
            <p class="text-3xl font-bold mt-2">{{ formatNumber(analytics?.total_sent || 0) }}</p>
            <p class="text-xs mt-2" :class="getTrendClass(analytics?.trends?.sent)">
              {{ getTrendLabel(analytics?.trends?.sent) }}
            </p>
          </div>

          <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
            <div class="flex items-center justify-between">
              <h3 class="text-sm font-medium text-muted-foreground">Messages Livrés</h3>
              <CheckCircleIcon class="w-8 h-8 text-success" />
            </div>
            <p class="text-3xl font-bold mt-2">{{ formatNumber(analytics?.total_delivered || 0) }}</p>
            <p class="text-xs mt-2" :class="getTrendClass(analytics?.trends?.delivered)">
              {{ getTrendLabel(analytics?.trends?.delivered) }}
            </p>
          </div>

          <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
            <div class="flex items-center justify-between">
              <h3 class="text-sm font-medium text-muted-foreground">Taux de Livraison</h3>
              <ChartBarIcon class="w-8 h-8 text-primary" />
            </div>
            <p class="text-3xl font-bold mt-2">{{ analytics?.delivery_rate?.toFixed(1) || 0 }}%</p>
            <p class="text-xs mt-2" :class="getDeliveryRateClass(analytics?.delivery_rate)">
              {{ getDeliveryRateLabel(analytics?.delivery_rate) }}
            </p>
          </div>

          <div class="rounded-lg border bg-card text-card-foreground shadow-sm p-6">
            <div class="flex items-center justify-between">
              <h3 class="text-sm font-medium text-muted-foreground">Coût Total</h3>
              <CreditCardIcon class="w-8 h-8 text-primary" />
            </div>
            <p class="text-3xl font-bold mt-2">{{ formatCurrency(analytics?.total_cost || 0) }}</p>
            <p class="text-xs mt-2" :class="getTrendClass(analytics?.trends?.cost)">
              {{ getTrendLabel(analytics?.trends?.cost) }}
            </p>
          </div>
        </div>

        <!-- Statistiques par fournisseur -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6 mb-8">
          <div class="rounded-lg border bg-card shadow-sm">
            <div class="p-6 border-b border-border">
              <h2 class="text-xl font-semibold">Répartition par Fournisseur</h2>
            </div>
            <div class="p-6">
              <div v-if="analytics?.by_provider && Object.keys(analytics.by_provider).length > 0" class="space-y-4">
                <div v-for="(data, provider) in analytics.by_provider" :key="provider" class="space-y-2">
                  <div class="flex items-center justify-between">
                    <span class="font-medium">{{ provider }}</span>
                    <span class="text-sm text-muted-foreground">{{ formatNumber(data.sent) }} messages</span>
                  </div>
                  <div class="w-full bg-muted rounded-full h-2">
                    <div
                      class="h-2 rounded-full"
                      :class="provider === 'Airtel' ? 'bg-red-500' : 'bg-yellow-500'"
                      :style="{ width: `${(data.sent / analytics.total_sent * 100).toFixed(1)}%` }"
                    ></div>
                  </div>
                  <div class="flex justify-between text-xs text-muted-foreground">
                    <span>Livrés: {{ data.delivered_rate?.toFixed(1) }}%</span>
                    <span>Coût: {{ formatCurrency(data.total_cost) }}</span>
                  </div>
                </div>
              </div>
              <div v-else class="text-center text-muted-foreground py-8">
                <p class="text-sm">Aucune donnée disponible</p>
              </div>
            </div>
          </div>

          <div class="rounded-lg border bg-card shadow-sm">
            <div class="p-6 border-b border-border">
              <h2 class="text-xl font-semibold">Crédits Restants</h2>
            </div>
            <div class="p-6">
              <div v-if="analytics?.credits_remaining !== undefined" class="space-y-4">
                <div class="text-center">
                  <p class="text-5xl font-bold text-primary">{{ formatNumber(analytics.credits_remaining) }}</p>
                  <p class="text-sm text-muted-foreground mt-2">crédits disponibles</p>
                </div>
                <div class="w-full bg-muted rounded-full h-3">
                  <div
                    class="h-3 rounded-full transition-all"
                    :class="getCreditBarClass(analytics.credits_remaining, analytics.initial_credits)"
                    :style="{ width: `${getCreditPercentage(analytics.credits_remaining, analytics.initial_credits)}%` }"
                  ></div>
                </div>
                <div class="flex justify-between text-xs text-muted-foreground">
                  <span>Utilisés: {{ formatNumber((analytics.initial_credits || 0) - analytics.credits_remaining) }}</span>
                  <span>Total: {{ formatNumber(analytics.initial_credits || 0) }}</span>
                </div>
              </div>
              <div v-else class="text-center text-muted-foreground py-8">
                <p class="text-sm">Aucune donnée disponible</p>
              </div>
            </div>
          </div>
        </div>

        <!-- Campagnes récentes et activité -->
        <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <!-- Campagnes récentes -->
        <div class="rounded-lg border bg-card text-card-foreground shadow-sm">
          <div class="p-6 border-b border-border">
            <h2 class="text-xl font-semibold">Campagnes Récentes</h2>
          </div>
          <div class="p-6">
            <div v-if="recentCampaigns.length > 0">
              <div v-for="campaign in recentCampaigns" :key="campaign.id" class="mb-4 last:mb-0 pb-4 last:pb-0 border-b last:border-b-0 border-border">
                <div class="flex items-center justify-between mb-2">
                  <h3 class="font-medium">{{ campaign.name }}</h3>
                  <span
                    class="text-xs px-2 py-1 rounded-full"
                    :class="getCampaignStatusClass(campaign.status)"
                  >
                    {{ getCampaignStatusLabel(campaign.status) }}
                  </span>
                </div>
                <div class="flex items-center gap-4 text-sm text-muted-foreground">
                  <span class="flex items-center gap-1">
                    <PaperAirplaneIcon class="w-4 h-4" />
                    {{ campaign.messages_sent || campaign.sent || 0 }} envoyés
                  </span>
                  <span class="flex items-center gap-1">
                    <CheckCircleIcon class="w-4 h-4" />
                    {{ campaign.delivery_rate || campaign.delivered || 0 }}% livrés
                  </span>
                </div>
              </div>
            </div>
            <div v-else class="text-center text-muted-foreground py-8">
              <p class="text-sm">Aucune campagne récente</p>
            </div>
          </div>
        </div>

        <!-- Activité récente -->
        <div class="rounded-lg border bg-card text-card-foreground shadow-sm">
          <div class="p-6 border-b border-border">
            <h2 class="text-xl font-semibold">Activité Récente</h2>
          </div>
          <div class="p-6">
            <div v-if="recentActivities.length > 0">
              <div v-for="activity in recentActivities" :key="activity.id" class="mb-4 last:mb-0 flex items-start gap-3">
                <component :is="activity.icon" class="w-5 h-5 text-muted-foreground flex-shrink-0 mt-0.5" />
                <div class="flex-1">
                  <p class="text-sm font-medium">{{ activity.title }}</p>
                  <p class="text-xs text-muted-foreground mt-1">{{ activity.time }}</p>
                </div>
              </div>
            </div>
            <div v-else class="text-center text-muted-foreground py-8">
              <p class="text-sm">Aucune activité récente</p>
            </div>
          </div>
        </div>
        </div>
      </div>
    </div>
  </MainLayout>
</template>

<script setup lang="ts">
import { computed, ref, onMounted, watch } from 'vue'
import { useAuthStore } from '@/stores/auth'
import MainLayout from '@/components/MainLayout.vue'
import {
  UsersIcon,
  ChartBarIcon,
  PaperAirplaneIcon,
  CheckCircleIcon,
  CreditCardIcon
} from '@heroicons/vue/24/outline'
import analyticsService from '@/services/analyticsService'
import { campaignService } from '@/services/campaignService'
import { contactService } from '@/services/contactService'

const authStore = useAuthStore()
const user = computed(() => authStore.user)

const periods = [
  { value: 'today', label: "Aujourd'hui" },
  { value: 'week', label: 'Cette semaine' },
  { value: 'month', label: 'Ce mois' },
  { value: 'year', label: 'Cette année' }
]

const selectedPeriod = ref('today')
const analytics = ref<any>(null)
const recentCampaigns = ref<any[]>([])
const recentActivities = ref<any[]>([])
const loading = ref(false)

function formatNumber(value: number): string {
  if (value >= 1000000) return `${(value / 1000000).toFixed(1)}M`
  if (value >= 1000) return `${(value / 1000).toFixed(1)}K`
  return value.toString()
}

function formatCurrency(value: number): string {
  return `${value.toLocaleString('fr-FR')} XAF`
}

function getTrendClass(trend?: number): string {
  if (!trend) return 'text-muted-foreground'
  if (trend > 0) return 'text-success'
  if (trend < 0) return 'text-destructive'
  return 'text-muted-foreground'
}

function getTrendLabel(trend?: number): string {
  if (!trend) return 'Aucun changement'
  const sign = trend > 0 ? '+' : ''
  return `${sign}${trend.toFixed(1)}% vs période précédente`
}

function getDeliveryRateClass(rate?: number): string {
  if (!rate) return 'text-muted-foreground'
  if (rate >= 95) return 'text-success'
  if (rate >= 85) return 'text-warning'
  return 'text-destructive'
}

function getDeliveryRateLabel(rate?: number): string {
  if (!rate) return 'Aucune donnée'
  if (rate >= 95) return 'Excellent'
  if (rate >= 85) return 'Bon'
  return 'À améliorer'
}

function getCreditPercentage(remaining: number, initial: number): number {
  if (!initial) return 0
  return (remaining / initial) * 100
}

function getCreditBarClass(remaining: number, initial: number): string {
  const percentage = getCreditPercentage(remaining, initial)
  if (percentage > 50) return 'bg-success'
  if (percentage > 20) return 'bg-warning'
  return 'bg-destructive'
}

async function loadDashboardData() {
  loading.value = true
  try {
    const [analyticsData, campaignsData] = await Promise.all([
      analyticsService.getDashboard(selectedPeriod.value),
      campaignService.getAll()
    ])

    // Mapper les données de l'API au format attendu par le template
    const data = analyticsData.data
    analytics.value = {
      total_sent: data.overview?.sms_sent || 0,
      total_delivered: data.overview?.sms_delivered || 0,
      total_failed: data.overview?.sms_failed || 0,
      delivery_rate: data.overview?.success_rate || 0,
      total_cost: data.overview?.total_cost || 0,
      campaigns_executed: data.overview?.campaigns_executed || 0,
      contacts_added: data.overview?.contacts_added || 0,
      trends: {
        sent: data.trends?.sms_sent_change || 0,
        delivered: data.trends?.success_rate_change || 0,
        cost: data.trends?.cost_change || 0,
        campaigns: data.trends?.campaigns_change || 0
      },
      by_provider: {
        Airtel: {
          sent: data.providers?.airtel?.count || 0,
          delivered_rate: data.providers?.airtel?.percentage || 0,
          total_cost: data.cost_analysis?.airtel_cost || 0
        },
        Moov: {
          sent: data.providers?.moov?.count || 0,
          delivered_rate: data.providers?.moov?.percentage || 0,
          total_cost: data.cost_analysis?.moov_cost || 0
        }
      },
      credits_remaining: user.value?.credits || 0,
      initial_credits: user.value?.initial_credits || user.value?.credits || 1000
    }

    // Utiliser les campagnes de l'API analytics si disponibles, sinon les campagnes récentes
    recentCampaigns.value = data.campaigns?.length > 0
      ? data.campaigns.slice(0, 3)
      : campaignsData.slice(0, 3)

    // Générer les activités récentes
    recentActivities.value = generateRecentActivities(campaignsData)
  } catch (err) {
    console.error('Error loading dashboard data:', err)
  } finally {
    loading.value = false
  }
}

watch(selectedPeriod, () => {
  loadDashboardData()
})

function generateRecentActivities(campaigns: any[]): any[] {
  const activities: any[] = []

  // Ajouter les campagnes récentes
  campaigns.slice(0, 4).forEach(campaign => {
    if (campaign.messages_sent || campaign.sent) {
      activities.push({
        id: `campaign-${campaign.id}`,
        icon: PaperAirplaneIcon,
        title: `Campagne "${campaign.name}" envoyée à ${campaign.messages_sent || campaign.sent} contacts`,
        time: formatRelativeTime(campaign.created_at)
      })
    }
  })

  return activities.slice(0, 4)
}

function formatRelativeTime(dateString?: string): string {
  if (!dateString) return 'Récemment'
  const date = new Date(dateString)
  const now = new Date()
  const diff = now.getTime() - date.getTime()
  const hours = Math.floor(diff / (1000 * 60 * 60))
  const days = Math.floor(diff / (1000 * 60 * 60 * 24))

  if (hours < 1) return 'Il y a quelques minutes'
  if (hours < 24) return `Il y a ${hours} heure${hours > 1 ? 's' : ''}`
  if (days === 1) return 'Il y a 1 jour'
  return `Il y a ${days} jours`
}

function getCampaignStatusClass(status: string): string {
  const lowerStatus = status?.toLowerCase()
  if (lowerStatus === 'active' || lowerStatus === 'actif') {
    return 'bg-success/10 text-success'
  }
  if (lowerStatus === 'scheduled' || lowerStatus === 'planifié') {
    return 'bg-warning/10 text-warning'
  }
  return 'bg-muted text-muted-foreground'
}

function getCampaignStatusLabel(status: string): string {
  const lowerStatus = status?.toLowerCase()
  if (lowerStatus === 'active' || lowerStatus === 'actif') return 'Active'
  if (lowerStatus === 'scheduled' || lowerStatus === 'planifié') return 'Planifiée'
  if (lowerStatus === 'completed' || lowerStatus === 'terminé') return 'Terminée'
  return status || 'Inconnu'
}

onMounted(() => {
  loadDashboardData()
})
</script>

// resources/src/pages/Dashboard.tsx
import { useEffect, useState } from "react";
import { Layout } from "@/components/layout/Layout";
import { MetricCard } from "@/components/ui/metric-card";
import { DataTable, Column, Action } from "@/components/ui/data-table";
import { useAppStore, Campaign } from "@/lib/store";
import { TrendingUp, Users, MessageSquare, BarChart3, DollarSign, Activity } from "lucide-react";
import { useToast } from "@/hooks/use-toast";
import analyticsService, { AnalyticsDashboard } from "@/services/analyticsService";

export default function Dashboard() {
  const { campaigns, loadCampaigns } = useAppStore();
  const { toast } = useToast();
  const [analytics, setAnalytics] = useState<AnalyticsDashboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState<string>('today');

  useEffect(() => {
    loadCampaigns();
    loadAnalytics();
  }, [loadCampaigns, period]);

  const loadAnalytics = async () => {
    try {
      setLoading(true);
      const { data } = await analyticsService.getDashboard(period);
      setAnalytics(data);
    } catch (error) {
      console.error('Failed to load analytics:', error);
      toast({
        title: "Erreur",
        description: "Impossible de charger les statistiques",
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const metrics = analytics ? [
    {
      title: "SMS Envoyés",
      value: analytics.overview.sms_sent.toLocaleString('fr-FR'),
      subtitle: `(${period === 'today' ? "Aujourd'hui" : "Période sélectionnée"})`,
      icon: MessageSquare,
      trend: {
        value: Math.abs(analytics.trends.sms_sent_change),
        label: "vs période précédente",
        isPositive: analytics.trends.sms_sent_change >= 0
      }
    },
    {
      title: "SMS Délivrés",
      value: analytics.overview.sms_delivered.toLocaleString('fr-FR'),
      icon: Activity,
      trend: {
        value: analytics.overview.success_rate,
        label: "taux de succès",
        isPositive: true
      }
    },
    {
      title: "Taux de Succès",
      value: `${analytics.overview.success_rate.toFixed(1)}%`,
      icon: TrendingUp,
      trend: {
        value: Math.abs(analytics.trends.success_rate_change),
        label: "vs période précédente",
        isPositive: analytics.trends.success_rate_change >= 0
      }
    },
    {
      title: "Coût Total",
      value: `${analytics.overview.total_cost.toLocaleString('fr-FR')} FCFA`,
      icon: DollarSign,
      trend: {
        value: Math.abs(analytics.trends.cost_change),
        label: "vs période précédente",
        isPositive: analytics.trends.cost_change <= 0
      }
    },
    {
      title: "Campagnes Exécutées",
      value: analytics.overview.campaigns_executed.toString(),
      icon: BarChart3,
      trend: {
        value: Math.abs(analytics.trends.campaigns_change),
        label: "vs période précédente",
        isPositive: analytics.trends.campaigns_change >= 0
      }
    },
    {
      title: "Contacts Ajoutés",
      value: analytics.overview.contacts_added.toLocaleString('fr-FR'),
      icon: Users,
      trend: {
        value: 0,
        label: "pendant la période",
        isPositive: true
      }
    }
  ] : [];

  const columns: Column<Campaign>[] = [
    {
      key: 'name',
      header: 'Nom de la Campagne',
    },
    {
      key: 'status',
      header: 'Statut',
    },
    {
      key: 'messages_sent',
      header: 'Messages Envoyés',
      render: (value) => value.toLocaleString('fr-FR')
    },
    {
      key: 'delivery_rate',
      header: 'Taux de Livraison',
      render: (value) => `${value}%`
    },
    {
      key: 'ctr',
      header: 'CTR',
      render: (value) => `${value}%`
    }
  ];

  const actions: Action<Campaign>[] = [
    {
      label: 'Voir',
      onClick: (campaign) => {
        toast({
          title: "Campagne sélectionnée",
          description: `Consultation de la campagne "${campaign.name}"`,
        });
      }
    },
    {
      label: 'Modifier',
      onClick: (campaign) => {
        toast({
          title: "Modification",
          description: `Édition de la campagne "${campaign.name}"`,
        });
      }
    }
  ];

  if (loading && !analytics) {
    return (
      <Layout title="Tableau de Bord">
        <div className="flex items-center justify-center h-64">
          <div className="text-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary mx-auto mb-4"></div>
            <p className="text-muted-foreground">Chargement des statistiques...</p>
          </div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout title="Tableau de Bord">
      <div className="space-y-6">
        {/* Period Selector */}
        <div className="flex justify-between items-center">
          <div>
            <h1 className="text-3xl font-bold">Tableau de Bord</h1>
            <p className="text-muted-foreground mt-1">Vue d'ensemble de vos campagnes SMS</p>
          </div>
          <select
            value={period}
            onChange={(e) => setPeriod(e.target.value)}
            className="px-4 py-2 border border-border rounded-lg bg-background focus:outline-none focus:ring-2 focus:ring-primary"
          >
            <option value="today">Aujourd'hui</option>
            <option value="yesterday">Hier</option>
            <option value="week">Cette semaine</option>
            <option value="month">Ce mois</option>
            <option value="last_7_days">7 derniers jours</option>
            <option value="last_30_days">30 derniers jours</option>
            <option value="year">Cette année</option>
          </select>
        </div>

        {/* Metrics Cards */}
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {metrics.map((metric, index) => (
            <MetricCard
              key={index}
              title={metric.title}
              value={metric.value}
              subtitle={metric.subtitle}
              icon={metric.icon}
              trend={metric.trend}
            />
          ))}
        </div>

        {/* Provider Distribution */}
        {analytics && (
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="bg-card rounded-lg border border-border p-6">
              <h2 className="text-xl font-semibold mb-4">Répartition par Opérateur</h2>
              <div className="space-y-4">
                <div>
                  <div className="flex justify-between items-center mb-2">
                    <span className="font-medium">Airtel</span>
                    <span className="text-sm text-muted-foreground">
                      {analytics.providers.airtel.count.toLocaleString('fr-FR')} SMS ({analytics.providers.airtel.percentage.toFixed(1)}%)
                    </span>
                  </div>
                  <div className="w-full bg-secondary rounded-full h-3">
                    <div
                      className="bg-red-500 h-3 rounded-full transition-all"
                      style={{ width: `${analytics.providers.airtel.percentage}%` }}
                    ></div>
                  </div>
                </div>
                <div>
                  <div className="flex justify-between items-center mb-2">
                    <span className="font-medium">Moov</span>
                    <span className="text-sm text-muted-foreground">
                      {analytics.providers.moov.count.toLocaleString('fr-FR')} SMS ({analytics.providers.moov.percentage.toFixed(1)}%)
                    </span>
                  </div>
                  <div className="w-full bg-secondary rounded-full h-3">
                    <div
                      className="bg-blue-500 h-3 rounded-full transition-all"
                      style={{ width: `${analytics.providers.moov.percentage}%` }}
                    ></div>
                  </div>
                </div>
              </div>
            </div>

            {/* Cost Analysis */}
            <div className="bg-card rounded-lg border border-border p-6">
              <h2 className="text-xl font-semibold mb-4">Analyse des Coûts</h2>
              <div className="space-y-3">
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Coût Airtel</span>
                  <span className="font-semibold">{analytics.cost_analysis.airtel_cost.toLocaleString('fr-FR')} FCFA</span>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Coût Moov</span>
                  <span className="font-semibold">{analytics.cost_analysis.moov_cost.toLocaleString('fr-FR')} FCFA</span>
                </div>
                <div className="border-t border-border pt-3 mt-3">
                  <div className="flex justify-between">
                    <span className="text-muted-foreground">Coût Moyen/SMS</span>
                    <span className="font-semibold">{analytics.overview.average_cost_per_sms.toFixed(2)} FCFA</span>
                  </div>
                </div>
                <div className="flex justify-between">
                  <span className="text-muted-foreground">Coût Quotidien Moyen</span>
                  <span className="font-semibold">{analytics.cost_analysis.average_daily_cost.toFixed(2)} FCFA</span>
                </div>
              </div>
            </div>
          </div>
        )}

        {/* Top Campaigns */}
        {analytics && analytics.campaigns.length > 0 && (
          <div className="bg-card rounded-lg border border-border p-6">
            <h2 className="text-xl font-semibold mb-4">Top 5 Campagnes</h2>
            <div className="space-y-3">
              {analytics.campaigns.map((campaign, index) => (
                <div key={campaign.id} className="flex items-center justify-between p-3 bg-secondary/50 rounded-lg">
                  <div className="flex items-center space-x-3">
                    <div className="flex items-center justify-center w-8 h-8 rounded-full bg-primary/10 text-primary font-semibold">
                      {index + 1}
                    </div>
                    <div>
                      <p className="font-medium">{campaign.name}</p>
                      <p className="text-sm text-muted-foreground">
                        {new Date(campaign.created_at).toLocaleDateString('fr-FR')}
                      </p>
                    </div>
                  </div>
                  <div className="text-right">
                    <p className="font-semibold">{campaign.messages_sent.toLocaleString('fr-FR')}</p>
                    <p className="text-sm text-muted-foreground">messages envoyés</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Recent Campaigns Table */}
        <div className="bg-card rounded-lg border border-border p-6">
          <h2 className="text-xl font-semibold mb-4">Campagnes Récentes</h2>
          <DataTable
            data={campaigns}
            columns={columns}
            actions={actions}
            searchPlaceholder="Rechercher des campagnes..."
          />
        </div>
      </div>
    </Layout>
  );
}
